### ISSUE TITLE
[FR] Disabling auto-indent completely

### ISSUE THREAD

**Issue by ImportTaste** [alondmnt/joplin-plugin-space-indenter#3]
There is currently a setting for disabling smart indent, but what I really want is this: Every time I hit enter, I want the caret (aka text cursor) to be in the left-most position, column 0, with no spaces or tabs being added to the line.

# Use-case

1. Honestly, I just find it annoying at times, I prefer to manually indent things.
2. I keep a dream journal in Joplin and I often "write" them down by reaching for my wireless keyboard and typing into it with my eyes closed. In my drowsy state, spacebar and enter get hit a lot more often than I intend, so what'll happen is that new lines will get more and more indented.

**Comment by alondmnt** [comment]
I recommend checking the beta markdown editor (`Joplin settings --> General --> Opt-in to the editor beta`). Its behaviour is a bit different from the old / default editor, and I think that it will solve your issue.

**Comment by taw00** [comment]
What he means is that if he types this …

lkjsdlfjsdfkj
   aslkdjfsldjsdjf
   HE WANTS THIS TO NOT START THERE.

This comment input field does the same thing that annoys him. The caret starts at the starting point of the previous line. Instead, he wants the caret to go to column zero. Always. Right now (smart indenting behavior notwithstanding), it does not.

**Comment by alondmnt** [comment]
Thanks for the explanation. I understood the the original post the same way. But for some reason, while implementing a fix it occurred to me that in CM6 the default behaviour is different. Of course, I couldn't reproduce it now. Please try v0.2.4 (published on GH and on the Joplin store now), activate the beta editor (required), and try to disable auto indent from the settings. Let me know if this works for you.

**Comment by taw00** [comment]
Seems to be resolved.
